apiVersion: v1
kind: Secret
metadata:
  name: iot-platform-secret
  namespace: iot-platform
type: Opaque
data:
  # Base64エンコードされた値
  # echo -n "postgres" | base64
  DATABASE_PASSWORD: cG9zdGdyZXM=
  # echo -n "test" | base64
  AWS_ACCESS_KEY_ID: dGVzdA==
  # echo -n "test" | base64
  AWS_SECRET_ACCESS_KEY: dGVzdA==
  # echo -n "your_secret_key_base_here" | base64
  SECRET_KEY_BASE: eW91cl9zZWNyZXRfa2V5X2Jhc2VfaGVyZQ==
  # echo -n "your_master_key_here" | base64
  RAILS_MASTER_KEY: eW91cl9tYXN0ZXJfa2V5X2hlcmU=
